name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        run: |
          sudo apt-get update
          sudo apt-get install -y golang

      - name: Install Python
        run: |
          sudo apt-get install -y python3 python3-pip

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Get Latest Hugo Version
        id: hugo_version
        run: |
          # Fetch the latest release tag from Hugo GitHub repository
          latest_version=$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          
          # Minimum version check
          minimum_version=0.124.0

          # Compare versions and ensure minimum version requirement
          if [ "$(printf '%s\n' "$minimum_version" "$latest_version" | sort -V | head -n1)" = "$minimum_version" ]; then
            echo "Using latest version: $latest_version"
          else
            echo "Using minimum version: $minimum_version"
            latest_version=$minimum_version
          fi

          echo "Hugo version to install: $latest_version"
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Install Latest Hugo
        run: |
          # Download and install the determined Hugo version
          wget https://github.com/gohugoio/hugo/releases/download/v${{ env.latest_version }}/hugo_${{ env.latest_version }}_Linux-64bit.tar.gz
          tar -xzf hugo_${{ env.latest_version }}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/

      - name: Cache Hugo Modules
        uses: actions/cache@v3
        with:
          path: .hugo_mod/cache
          key: ${{ runner.os }}-hugo-mod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugo-mod-

      - name: Clean Public Directory
        run: rm -rf public

      - name: Hugo Build
        run: |
          hugo mod get
          hugo --version
          hugo

      - name: Clean Server Directory
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_SERVER "mkdir -p /var/www/ilmenauerschachverein/vm24"
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_SERVER "rm -rf /var/www/ilmenauerschachverein/vm24/*"

      - name: Upload to External Server via SCP
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
        run: |
          sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -r public/* $SSH_USERNAME@$SSH_SERVER:/var/www/ilmenauerschachverein/vm24
